name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build Docker image
      run: docker build -t your-docker-username/your-image-name:latest .

    - name: Push Docker image to Docker Hub
      run: docker push your-docker-username/your-image-name:latest

    - name: Logout from Docker Hub
      run: docker logout
